version: "2"
services:
  zway:
    build:
      context: .
    image: eugenmayer/zway
    ports:
      - "8083:8083"
    volumes:
      - "/z-way-data:/opt/z-way-server"
      - "/z-way-data/config:/opt/z-way-server/config"
    devices:
      - "/dev/ttyACM0:/dev/ttyAMA0"
    restart: unless-stopped
